name: 1 - [PLAN] Terraform Plan & Testing

on: push

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  TF_VAR_aws_key_pub: ${{secrets.TF_VAR_aws_key_pub}}
  TF_VAR_azure_key_pub: ${{secrets.TF_VAR_azure_key_pub}}

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    
    - name: Terraform Init
      id: init
      run: terraform init
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Plan
      id: plan
      run: terraform plan

  terraform_test:
    needs: terraform_plan
    name: Terraform Unit Testing & Integration Testing
    runs-on: ubuntu-latest
    outputs:
      tests-passed: ${{ job.status == 'success' }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Unit Testing & Integration Testing
      id: test
      run: terraform test
